% script STRAIGHTaudio2objectWrapper

% rather than running addpaths every time, it's easiest to add them to your startup.m
addpath(% 'HERE ADD YOUR PATH TO \TANDEM-STRAIGHT\TandemSTRAIGHTnewGUIoldMorphing')
addpath(% 'HERE ADD YOUR PATH TO \codeVocalAnalyses')
addpath(% 'HERE ADD YOUR PATH TO \codeDependencies


%work on all wav files in present directory
SAcCresynth = 0; 
filepath = pwd;
lstruct=dir('./*.wav');
filein = {lstruct.name};
 
%work on a list of audio files
%SAcCresynth = 0; 
% filein = {'1_BrolaskiJT_Elegy_NonBinary.mp3',...
%     '1_MillayE_LoveisNotAll_Female.mp3',...
%     '1_WhitmanW_America_Male.mp3',...
%     '2_SextonA_MusicSwimsBackToMe_Female.m4a',...
%     '2_YeatsWB_LakeIsleofInnisfree_Male.MP3',...
%     '3_FrostR_TheRoadNotTaken_Male.wav',...
%     '3_PlathS_LadyLazarus_Female.mp3',...
%     '4_EliotTS_WastelandPartFive_Male.mp3',...
%     '4_JordanJ_APoemAboutIntelligence_Female.wav',...
%     '5_GinsbergA_HowlOpening_Male.wav',...
%     '5_GluckL_WildIris_Female.wav',...
%     '6_ArmantroutR_TheSubject_Female.mp3',...
%     '6_AshberyJ_AtNorthFarm_Male.mp3',...
%     '7_BarakaA_PoemForHalfWhite_Male.mp3',...
%     '7_MylesE_EachDefeat_Female.mp3',...
%     '8_BidartF_AnAmericaninHollywood_Male.mp3'};

for f = 1:length(filein)
  [STRAIGHTobject] = STRAIGHTaudio2object(filepath,filein{f},SAcCresynth);
%   close all
end

