
% run on all TANDEM-STRAIGHT object files in directory
lstruct=dir('./*_Sobj.mat');
filein = {lstruct.name};

% run on a list of TANDEM-STRAIGHT object files 
% filein = {'Millay_HerScatteredLook_SAcC_Sobj.mat',...
%     'Sexton_MusicSwimsBack_SAcC_Sobj.mat',...
%     'Plath_PeanutCrunching_SAcC_Sobj.mat',...
%     'Jordan_HowYouDoin_Sobj.mat',...
%     'Gluck_ReturnsfromOblivion_Sobj.mat',...
%     'Armantrout_JustTurnedHuman_Sobj.mat',...
%     'Myles_LetMeFryanEgg_Sobj.mat',...
%     'Whitman_Centre_SAcC_Sobj.mat',...
%     'Yeats_IWillArise_Sobj.mat',...
%     'Frost_KepttheFirst_Sobj.mat',...
%     'Eliot_AwfulDaring_Sobj.mat',...
%     'Ginsberg_Poverty_Sobj.mat',...
%     'Ashbery_SomeoneTraveling_Sobj.mat',...
%     'Baraka_HowDoYouSound_SAcC_Sobj.mat',...
%     'Bidart_CrazyNarratives_Sobj.mat'};

overwrite = 1;

xlsdata = [];
rowheader = cell(length(filein),1);
for f = 1:length(filein)
   disp(['Analyzing ' filein{f}]);
   %gentlefile = [gentleDir filein{f}(1:strfind(filein{f},'_Sobj')-1) 'gentle.csv']; %might use this in future
   [Sout] = vocAnal(filein{f},overwrite);
   
   a=Sout.analysis;
   rowheader{f} = filein{f};  
   xlsdata(f,:) = [a.dynamism a.speakingRate a.f0entropy a.complexityAllPauses a.complexitySyllables a.complexityPhrases a.pausecount a.pauserate a.pausemean100 a.f0mean a.f0range a.f0speed a.f0contour]; 
   colheader    = {'dynamism' 'speakingRate','f0entropy','complexityAllPauses','complexitySyllables','complexityPhrases','pausecount','pauserate','pausemean100','f0mean','f0range','f0speed','f0contour'};
   %could just do colheader once at end but safer to align with xlsdata
   
   %eval(['S' filein{f}(1:5) ' = Sout;']); clear Sout;
end

xlswrite('VocAnalStats.xls',xlsdata,'Sheet1','B2');     %Write data
xlswrite('VocAnalStats.xls',colheader,'Sheet1','B1');     %Write column header
xlswrite('VocAnalStats.xls',rowheader,'Sheet1','A2');      %Write row header
